"""This module implements the paired permutation tests for the theta waveform-shape control analysis.

Two tests are implemented, matching what the published control reports:

1. **Paired test across channels.** For each channel, the mean asymmetry under
   the baseline load and under the comparison load form a pair. The statistic is
   the mean paired difference; the null is generated by flipping the sign of
   each channel's difference independently, which is the exchangeability
   assumption behind a within-channel label swap.

2. **One-sample test against 0.5.** bycycle's ``time_ptsym`` and ``time_rdsym``
   are bounded on [0, 1] with 0.5 meaning a symmetric cycle, so "is the waveform
   symmetric at all" is a separate question from "does symmetry differ by load".
   Same sign-flip machinery, applied to ``value - 0.5``.

Every test returns an effect size and a bootstrap confidence interval alongside
the p-value. A null result needs a precision estimate to interpret, because a
p-value alone does not distinguish no difference from insufficient power.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Literal

import numpy as np
from numpy.typing import ArrayLike, NDArray

Statistic = Literal["mean_diff", "t_stat"]


@dataclass(frozen=True)
class TestResult:
    """Outcome of one permutation test."""

    metric: str
    test: str
    n_units: int
    observed: float
    p_value: float
    n_permutations: int
    statistic: str
    effect_size_dz: float
    ci_lower: float
    ci_upper: float
    ci_level: float
    mean_baseline: float | None = None
    mean_comparison: float | None = None
    p_value_adjusted: float | None = None
    adjustment: str | None = None

    def as_row(self) -> dict[str, object]:
        return asdict(self)


def _as_1d(values: ArrayLike, name: str) -> NDArray[np.float64]:
    array = np.asarray(values, dtype=np.float64).ravel()
    if array.size == 0:
        raise ValueError(f"{name} is empty")
    if not np.isfinite(array).all():
        raise ValueError(f"{name} contains non-finite values; drop or impute before testing")
    return array


def _statistic(differences: NDArray[np.float64], kind: Statistic) -> NDArray[np.float64]:
    """Compute the test statistic along the last axis.

    ``mean_diff`` is the raw mean difference. ``t_stat`` standardises by the
    standard error, which makes the statistic scale-free and is the closer match
    to a permutation-based paired t-test.
    """
    if kind == "mean_diff":
        return differences.mean(axis=-1)
    if kind == "t_stat":
        n = differences.shape[-1]
        mean = differences.mean(axis=-1)
        sd = differences.std(axis=-1, ddof=1)
        with np.errstate(divide="ignore", invalid="ignore"):
            stat = np.where(sd > 0, mean / (sd / np.sqrt(n)), 0.0)
        return stat
    raise ValueError(f"unknown statistic: {kind!r}")


def _sign_flip_null(
    differences: NDArray[np.float64],
    n_permutations: int,
    statistic: Statistic,
    rng: np.random.Generator,
    block_size: int = 2000,
) -> NDArray[np.float64]:
    """Sign-flip null distribution, generated in blocks to bound memory.

    A full ``(n_permutations, n_units)`` sign matrix is fine for a few hundred
    channels but grows without bound if the unit of analysis changes, so the
    permutations are drawn in blocks.
    """
    n_units = differences.size
    null = np.empty(n_permutations, dtype=np.float64)
    filled = 0
    while filled < n_permutations:
        take = min(block_size, n_permutations - filled)
        signs = rng.choice(np.array([-1.0, 1.0]), size=(take, n_units))
        null[filled : filled + take] = _statistic(signs * differences, statistic)
        filled += take
    return null


def _permutation_p_value(observed: float, null: NDArray[np.float64]) -> float:
    """Two-sided p-value with the add-one correction.

    Using ``(1 + count) / (1 + n)`` rather than ``count / n`` keeps the p-value
    strictly positive: an exact zero would imply more resolution than the number
    of permutations supports.
    """
    exceedances = int(np.sum(np.abs(null) >= abs(observed) - 1e-12))
    return (1.0 + exceedances) / (1.0 + null.size)


def _bootstrap_ci(
    values: NDArray[np.float64],
    n_resamples: int,
    rng: np.random.Generator,
    level: float = 0.95,
) -> tuple[float, float]:
    """Percentile bootstrap CI for the mean."""
    n = values.size
    means = np.empty(n_resamples, dtype=np.float64)
    for i in range(n_resamples):
        means[i] = values[rng.integers(0, n, size=n)].mean()
    alpha = (1.0 - level) / 2.0
    lower, upper = np.quantile(means, [alpha, 1.0 - alpha])
    return float(lower), float(upper)


def _cohens_dz(differences: NDArray[np.float64]) -> float:
    sd = differences.std(ddof=1)
    if sd == 0:
        return 0.0
    return float(differences.mean() / sd)


def paired_permutation_test(
    baseline: ArrayLike,
    comparison: ArrayLike,
    *,
    metric: str,
    n_permutations: int = 10_000,
    statistic: Statistic = "mean_diff",
    seed: int = 0,
    ci_level: float = 0.95,
    n_bootstrap: int = 5_000,
) -> TestResult:
    """Two-sided paired sign-flip permutation test.

    Parameters
    ----------
    baseline, comparison
        Per-unit (channel) summary values under each condition, aligned
        elementwise. Units with a missing value in either condition must be
        dropped upstream, since the test relies on the pairing.
    """
    x = _as_1d(baseline, "baseline")
    y = _as_1d(comparison, "comparison")
    if x.size != y.size:
        raise ValueError(f"unequal pair counts: {x.size} baseline vs {y.size} comparison")
    if x.size < 2:
        raise ValueError("paired test needs at least 2 units")

    differences = y - x
    rng = np.random.default_rng(seed)

    observed = float(_statistic(differences, statistic))
    null = _sign_flip_null(differences, n_permutations, statistic, rng)
    p_value = _permutation_p_value(observed, null)
    ci_lower, ci_upper = _bootstrap_ci(differences, n_bootstrap, rng, ci_level)

    return TestResult(
        metric=metric,
        test="paired_sign_flip",
        n_units=int(differences.size),
        observed=observed,
        p_value=p_value,
        n_permutations=n_permutations,
        statistic=statistic,
        effect_size_dz=_cohens_dz(differences),
        ci_lower=ci_lower,
        ci_upper=ci_upper,
        ci_level=ci_level,
        mean_baseline=float(x.mean()),
        mean_comparison=float(y.mean()),
    )


def one_sample_permutation_test(
    values: ArrayLike,
    *,
    metric: str,
    null_value: float = 0.5,
    n_permutations: int = 10_000,
    statistic: Statistic = "mean_diff",
    seed: int = 0,
    ci_level: float = 0.95,
    n_bootstrap: int = 5_000,
) -> TestResult:
    """Two-sided sign-flip test of ``mean(values) == null_value``."""
    array = _as_1d(values, "values")
    if array.size < 2:
        raise ValueError("one-sample test needs at least 2 units")

    centered = array - null_value
    rng = np.random.default_rng(seed)

    observed = float(_statistic(centered, statistic))
    null = _sign_flip_null(centered, n_permutations, statistic, rng)
    p_value = _permutation_p_value(observed, null)
    ci_lower, ci_upper = _bootstrap_ci(array, n_bootstrap, rng, ci_level)

    return TestResult(
        metric=metric,
        test=f"one_sample_vs_{null_value:g}",
        n_units=int(array.size),
        observed=observed,
        p_value=p_value,
        n_permutations=n_permutations,
        statistic=statistic,
        effect_size_dz=_cohens_dz(centered),
        ci_lower=ci_lower,
        ci_upper=ci_upper,
        ci_level=ci_level,
        mean_baseline=float(array.mean()),
    )


def holm_bonferroni(results: list[TestResult]) -> list[TestResult]:
    """Apply Holm-Bonferroni correction across a family of tests.

    Two metrics are tested per analysis, so the correction is small, but
    reporting uncorrected p-values across the two metrics would understate the
    family-wise error rate.
    """
    if not results:
        return []

    order = sorted(range(len(results)), key=lambda index: results[index].p_value)
    m = len(results)
    adjusted: list[float] = [0.0] * m
    running_max = 0.0
    for rank, idx in enumerate(order):
        value = min(1.0, (m - rank) * results[idx].p_value)
        running_max = max(running_max, value)
        adjusted[idx] = running_max

    corrected: list[TestResult] = []
    for idx, result in enumerate(results):
        corrected.append(
            TestResult(
                **{
                    **result.as_row(),
                    "p_value_adjusted": adjusted[idx],
                    "adjustment": "holm-bonferroni",
                }
            )
        )
    return corrected
